import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, balanced_accuracy_score, classification_report
import os

print("Loading trace data...")
df = pd.read_csv("trace_decaying_lfu.csv")

# Filter to discriminative phases ONLY
# In Phases 1,3,4,5 every page is accessed every epoch -> all get label=1 -> no signal
df_train = df[df["phase"].isin([2, 6])].copy()

# Build MultiIndex for O(log N) lookups
print("Building index...")
df_lookup = df.set_index(["epoch", "page_idx"]).sort_index()

LOOKAHEAD_K = 10
ACCESS_THRESHOLD = 6


def label_page(epoch, page_idx, phase_at_T):
    """Label a page at a given epoch using K-step lookahead."""
    count = 0
    for k in range(1, LOOKAHEAD_K + 1):
        try:
            row = df_lookup.loc[(epoch + k, page_idx)]
        except KeyError:
            return None  # epoch doesn't exist (end of workload)

        # Guard against phase boundary crossing
        if row["phase"] != phase_at_T:
            return None

        count += int(row["accessed"])
    return 1 if count >= ACCESS_THRESHOLD else 0


FEATURE_COLS = [
    "smooth_frequency",  # index 0
    "access_count",  # index 1
    "momentum",  # index 2
    "migration_history",  # index 3
    "epochs_since_access",  # index 4
    "hot_ratio",  # index 5
    "access_frequency_ratio",  # index 6
]

print("Labeling data...")
records = []
epochs_in_scope = df_train["epoch"].unique()
pages_in_scope = df_train["page_idx"].unique()

for epoch in epochs_in_scope:
    for page_idx in pages_in_scope:
        try:
            row = df_lookup.loc[(epoch, page_idx)]
        except KeyError:
            continue

        phase_at_T = row["phase"]
        label = label_page(epoch, page_idx, phase_at_T)
        if label is None:
            continue  # boundary epoch or missing -> skip

        records.append(
            {
                "smooth_frequency": row["smooth_frequency"],
                "access_count": row["access_count"],
                "momentum": row["momentum"],
                "migration_history": row["migration_history"],
                "epochs_since_access": row["epochs_since_access"],
                "hot_ratio": row["hot_ratio"],
                "access_frequency_ratio": row["access_frequency_ratio"],
                "label": label,
            }
        )

df_labeled = pd.DataFrame(records)
X = df_labeled[FEATURE_COLS].values
y = df_labeled["label"].values

print(f"Total labeled samples: {len(df_labeled)}")
print(
    f"Class balance: {np.mean(y):.3f} label=1 (hot), {1-np.mean(y):.3f} label=0 (cold)"
)

print("Training model...")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# class_weight='balanced' down-weights the cold-page majority automatically
model = LogisticRegression(C=1.0, max_iter=1000, class_weight="balanced")
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(f"\nF1 Score: {f1_score(y_test, y_pred):.3f}")
print(f"Balanced Accuracy: {balanced_accuracy_score(y_test, y_pred):.3f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("\nWeight analysis:")
for i, col in enumerate(FEATURE_COLS):
    print(f"  {col:25s} -> weight = {model.coef_[0][i]:+.4f}")
print(f"  {'bias':25s} -> {model.intercept_[0]:+.4f}")

weights = model.coef_[0]
bias = model.intercept_[0]
means = scaler.mean_
stds = scaler.scale_

# Guard: if any std is near-zero, clamp to 1.0
for i in range(len(stds)):
    if stds[i] < 1e-10:
        print(
            f"WARNING: Feature '{FEATURE_COLS[i]}' has near-zero std ({stds[i]:.2e}). Clamping to 1.0"
        )
        stds[i] = 1.0

out_path = "../daemon/ml_weights.h"
with open(out_path, "w") as f:
    f.write("#pragma once\n")
    f.write("// Auto-generated by ml/label_and_train.py — DO NOT EDIT\n")
    f.write(f'// Feature order: {", ".join(FEATURE_COLS)}\n')
    f.write(f"constexpr int ML_NUM_FEATURES = {len(FEATURE_COLS)};\n\n")
    f.write(
        f'constexpr double ML_WEIGHTS[ML_NUM_FEATURES] = {{{", ".join(f"{w:.10f}" for w in weights)}}};\n'
    )
    f.write(f"constexpr double ML_BIAS = {bias:.10f};\n\n")
    f.write(
        f'constexpr double ML_SCALER_MEAN[ML_NUM_FEATURES] = {{{", ".join(f"{m:.10f}" for m in means)}}};\n'
    )
    f.write(
        f'constexpr double ML_SCALER_STD[ML_NUM_FEATURES]  = {{{", ".join(f"{s:.10f}" for s in stds)}}};\n'
    )

print(f"\nExported to {out_path}")
