#pragma once
// Auto-generated by ml/label_and_train_v2.py — DO NOT EDIT
// Feature order: access_count, smooth_frequency, momentum, migration_history, epochs_since_access, hot_ratio, access_frequency_ratio, aci
constexpr int ML_NUM_FEATURES = 8;

constexpr double ML_WEIGHTS[ML_NUM_FEATURES] = {-0.1439918785, 0.1305052386, -0.3081748756, 0.0000000000, 0.0000000000, 0.3371134134, 0.4468972897, 0.4066146945};
constexpr double ML_BIAS = 0.3054998609;

constexpr double ML_SCALER_MEAN[ML_NUM_FEATURES] = {750.3455559200, 92.3797713657, 8.2882509367, 0.0000000000, 0.0000000000, 50.2869054976, 0.4323195768, 287969.5251283153};
constexpr double ML_SCALER_STD[ML_NUM_FEATURES]  = {942.4641559488, 100.6532806563, 26.3762473006, 1.0000000000, 1.0000000000, 52.5575233483, 0.3113296821, 443080.2727668207};
