import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, balanced_accuracy_score, classification_report
import os

traces = {
    'bfs':       'train_bfs_128k.csv',
    'backprop':  'train_backprop_10000.csv',
    'hotspot':   'train_hotspot_256.csv'
}

print("Loading trace data...")
dfs = []
for name, path in traces.items():
    if os.path.exists(path):
        df = pd.read_csv(path)
        df['workload'] = name
        dfs.append(df)
    else:
        print(f"WARNING: Trace file {path} not found. Skipping {name}.")

if not dfs:
    print("No trace files found. Exiting.")
    exit(1)

df_all = pd.concat(dfs, ignore_index=True)

df_filtered = df_all.copy()

df_labeled = df_all.copy()
df_labeled['label'] = df_labeled['is_hot']

FEATURE_COLS = [
    "access_count",
    "smooth_frequency",
    "momentum",
    "migration_history",
    "epochs_since_access",
    "hot_ratio",
    "access_frequency_ratio",
    "aci",
]

df_all["access_count"] = np.log1p(df_all["access_count"])

# Skipped manual labeling loop because data is pre-labeled

print("\nBalancing workload datasets...")
MAX_SAMPLES = 330000

balanced_dfs = []
for w in df_labeled['workload'].unique():
    df_w = df_labeled[df_labeled['workload'] == w]
    if len(df_w) > MAX_SAMPLES:
        print(f"  Downsampling {w} from {len(df_w)} to {MAX_SAMPLES}")
        df_w = df_w.sample(n=MAX_SAMPLES, random_state=42)
    balanced_dfs.append(df_w)

df_labeled = pd.concat(balanced_dfs, ignore_index=True)
print(f"\nTotal labeled samples (after balancing): {len(df_labeled)}")
for wl in df_labeled['workload'].unique():
    subset = df_labeled[df_labeled['workload'] == wl]
    print(f"  {wl}: {len(subset)} samples ({np.mean(subset['label']):.3f} positive rate)")


def train_and_eval(train_df, test_df, name):
    X_tr = train_df[FEATURE_COLS].values
    y_tr = train_df["label"].values
    X_te = test_df[FEATURE_COLS].values
    y_te = test_df["label"].values
    
    scaler = StandardScaler()
    X_tr_scaled = scaler.fit_transform(X_tr)
    X_te_scaled = scaler.transform(X_te)
    
    model = LogisticRegression(C=0.01, class_weight='balanced', max_iter=2000)
    model.fit(X_tr_scaled, y_tr)
    
    y_pred = model.predict(X_te_scaled)
    acc = balanced_accuracy_score(y_te, y_pred)
    f1 = f1_score(y_te, y_pred)
    print(f"[{name}] Balanced Acc: {acc:.3f} | F1: {f1:.3f}")
    return model, scaler

# Removed LOOCV loop since workloads changed

print("\n--- Final Model (Combined Data) ---")
train_df, test_df = train_test_split(df_labeled, test_size=0.2, stratify=df_labeled["label"], random_state=42)
final_model, final_scaler = train_and_eval(train_df, test_df, "Train: Combined -> Test: 20% Held-out")

print("\nWeight analysis (Final Model):")
weights = final_model.coef_[0]
bias = final_model.intercept_[0]
means = final_scaler.mean_
stds = final_scaler.scale_

for i, col in enumerate(FEATURE_COLS):
    print(f"  {col:25s} -> weight = {weights[i]:+.4f}")
print(f"  {'bias':25s} -> {bias:+.4f}")

# Guard: if any std is near-zero, clamp to 1.0
for i in range(len(stds)):
    if stds[i] < 1e-10:
        stds[i] = 1.0

out_path = "ml_weights.h"
with open(out_path, "w") as f:
    f.write("#pragma once\n")
    f.write("// Auto-generated by ml/label_and_train_v2.py — DO NOT EDIT\n")
    f.write(f'// Feature order: {", ".join(FEATURE_COLS)}\n')
    f.write(f"constexpr int ML_NUM_FEATURES = {len(FEATURE_COLS)};\n\n")
    f.write(f'constexpr double ML_WEIGHTS[ML_NUM_FEATURES] = {{{", ".join(f"{w:.10f}" for w in weights)}}};\n')
    f.write(f"constexpr double ML_BIAS = {bias:.10f};\n\n")
    f.write(f'constexpr double ML_SCALER_MEAN[ML_NUM_FEATURES] = {{{", ".join(f"{m:.10f}" for m in means)}}};\n')
    f.write(f'constexpr double ML_SCALER_STD[ML_NUM_FEATURES]  = {{{", ".join(f"{s:.10f}" for s in stds)}}};\n')

print(f"\nExported to {out_path}")
