#pragma once
// Auto-generated by ml/label_and_train.py — DO NOT EDIT
// Feature order: smooth_frequency, access_count, momentum, migration_history, epochs_since_access, hot_ratio, access_frequency_ratio
constexpr int ML_NUM_FEATURES = 7;

constexpr double ML_WEIGHTS[ML_NUM_FEATURES] = {7.3026873752, 0.0762022780, -0.4532685749, 0.0542141763, -0.4499962468, 0.3233405509, -2.5800863047};
constexpr double ML_BIAS = -8.8062437903;

constexpr double ML_SCALER_MEAN[ML_NUM_FEATURES] = {0.5691572169, 240.9147970027, -0.0162982129, 1.8654871422, 38.2690220389, 0.0538233026, 0.2863680578};
constexpr double ML_SCALER_STD[ML_NUM_FEATURES]  = {0.5829987916, 145.0362385733, 0.0642755695, 4.5299860902, 27.0946740629, 0.2268521163, 0.2945369562};
