#pragma once
// Auto-generated by ml/label_and_train.py — DO NOT EDIT
// Feature order: smooth_frequency, momentum, migration_history, epochs_since_access, hot_ratio, access_frequency_ratio, aci
constexpr int ML_NUM_FEATURES = 7;

constexpr double ML_WEIGHTS[ML_NUM_FEATURES] = {26.3272501084, -1.2922566201, -0.0249251225, -0.8602741609, 16.0178411487, 26.1842303745, 25.6036503295};
constexpr double ML_BIAS = -0.5695227350;

constexpr double ML_SCALER_MEAN[ML_NUM_FEATURES] = {0.9270316982, 0.0041123902, 6.6535505218, 95.9244555139, 0.4143411853, 0.0010780919, 11911.4598925118};
constexpr double ML_SCALER_STD[ML_NUM_FEATURES]  = {22.1866132396, 0.9466845942, 4.4840702700, 78.4652812488, 11.2273946269, 0.0257274171, 290062.0478674339};
