#pragma once
// Auto-generated by ml/label_and_train.py — DO NOT EDIT
// Feature order: smooth_frequency, momentum, migration_history, epochs_since_access, hot_ratio, access_frequency_ratio, aci
constexpr int ML_NUM_FEATURES = 7;

constexpr double ML_WEIGHTS[ML_NUM_FEATURES] = {5.9752128887, -1.5431437778, -0.2828424389, -3.3313917802, 0.2050473949, 8.2691200083, 4.2790825236};
constexpr double ML_BIAS = -5.2611268055;

constexpr double ML_SCALER_MEAN[ML_NUM_FEATURES] = {0.5626034703, 0.0158852581, 3.8811263028, 62.9207313503, 0.2076591266, 0.0019323254, 1877.6125831398};
constexpr double ML_SCALER_STD[ML_NUM_FEATURES]  = {9.2173744888, 2.2520199597, 3.7962921036, 43.7354788710, 5.1016395777, 0.0301028782, 32227.3794317958};
